name: Build Example

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ["examplekts", "examplegroovy"]
        task: ["assemble", "uploadToAlpakaTeschtRelease --alpaka-dryrun"]
    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v4.1.1

      # Setup JDK environment
      - name: Set up JDK
        uses: actions/setup-java@v4.3.0
        with:
          distribution: 'zulu'
          java-version: '17'

      # Run the Gradle task
      - name: Run :${{ matrix.module }}:${{ matrix.task }}
        run: ./gradlew clean :${{ matrix.module }}:${{ matrix.task }}
