name: Build Example

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: ["exampleKts", "exampleGroovy"]
        task: ["assemble", "assembleAndPublishToAlpakaTeschtRelease -Palpaka.dryRun=true"]
    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v6.0.2

      # Setup JDK environment
      - name: Set up JDK
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'zulu'
          java-version: '17'

      # Run the Gradle task
      - name: Run :${{ matrix.module }}:${{ matrix.task }}
        run: ./gradlew clean :${{ matrix.module }}:${{ matrix.task }}

  test-publication:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Set up JDK
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant permission to execute
        run: chmod +x gradlew

      - name: Test Publication
        run: |
          echo "${{secrets.MAVEN_SIGNING_KEY_ARMOR_ASC}}" > ./signingkey.asc
          gpg --quiet --output $GITHUB_WORKSPACE/signingkey.gpg --dearmor ./signingkey.asc
          ./gradlew :alpaka:plugin:publishToMavenLocal -Psigning.secretKeyRingFile=$GITHUB_WORKSPACE/signingkey.gpg -Psigning.password='${{secrets.MAVEN_SIGNING_KEY_PASSPHRASE}}' -Psigning.keyId=${{secrets.MAVEN_SIGNING_KEY_ID}} -PmavenCentralUsername=X -PmavenCentralPassword=X -PgithubRefName=test
